// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Weather_Forecast

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void UpandDown_Animation( lv_obj_t *TargetObject, int delay);
void ImgZoom_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen( lv_event_t * e);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_LabelMainScreenCityName;
lv_obj_t *ui_LabelMainScreenLocation;
lv_obj_t *ui_ImageMainScreenLocation;
lv_obj_t *ui_LabelMainScreenTemperature;
lv_obj_t *ui_ImageMainScreenCelsius;
lv_obj_t *ui_ImageMainScreenSunny;
lv_obj_t *ui_LabelMainScreenTemperatureRange;
lv_obj_t *ui_ImageMainScreenCelsius2;
lv_obj_t *ui_LabelMainScreenSunny;
lv_obj_t *ui_LabelMainScreenMildPollution;
lv_obj_t *ui_PanelMainScreenCurrent;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime1;
lv_obj_t *ui_LabelPanelMainScreenCurrent1;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp1;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime2;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime3;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime4;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime5;
lv_obj_t *ui_LabelPanelMainScreenCurrent2;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp2;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius1;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius2;
lv_obj_t *ui_LabelPanelMainScreenCurrent3;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp3;
lv_obj_t *ui_LabelPanelMainScreenCurrent4;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp4;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius3;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp5;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius4;
lv_obj_t *ui_LabelPanelMainScreenCurrent5;
lv_obj_t *ui_PanelMainScreenCurrent1;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime6;
lv_obj_t *ui_LabelPanelMainScreenCurrent6;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp6;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime7;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime8;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime9;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime10;
lv_obj_t *ui_LabelPanelMainScreenCurrent7;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp7;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius5;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius6;
lv_obj_t *ui_LabelPanelMainScreenCurrent8;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp8;
lv_obj_t *ui_LabelPanelMainScreenCurrent9;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp9;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius7;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp10;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius8;
lv_obj_t *ui_LabelPanelMainScreenCurrent10;
lv_obj_t *ui_LabelPanelMainScreenCurrent11;
lv_obj_t *ui_LabelPanelMainScreenCurrent12;
lv_obj_t *ui_LabelPanelMainScreenCurrent13;
lv_obj_t *ui_LabelPanelMainScreenCurrent14;
lv_obj_t *ui_LabelPanelMainScreenCurrent15;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius9;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp11;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp12;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp13;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp14;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp15;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius10;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius11;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius12;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius13;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius14;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot1;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot2;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot3;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot4;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot5;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot6;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot7;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot8;
lv_obj_t *ui_LabelPanelMainScreenCurrent1dot9;
lv_obj_t *ui_PanelMainScreenCurrent2;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime11;
lv_obj_t *ui_LabelPanelMainScreenCurrent16;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp16;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime12;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime13;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime14;
lv_obj_t *ui_ImagePanelMainScreenCurrentTime15;
lv_obj_t *ui_LabelPanelMainScreenCurrent17;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp17;
lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius15;
lv_obj_t *ui_LabelPanelMainScreenCurrent18;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp18;
lv_obj_t *ui_LabelPanelMainScreenCurrent19;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp19;
lv_obj_t *ui_LabelPanelMainScreenCurrentTemp20;
lv_obj_t *ui_LabelPanelMainScreenCurrent20;
lv_obj_t *ui____initial_weather_actions0;
const lv_img_dsc_t *ui_imgset_sunny_[1] = {&ui_img_sunny_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void UpandDown_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 600);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, -5, 5 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 600);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);

}
void ImgZoom_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, 0, 10 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 1000);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      UpandDown_Animation(ui_ImageMainScreenLocation, 0);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      ImgZoom_Animation(ui_ImageMainScreenSunny, 0);
}
}

///////////////////// SCREENS ////////////////////

void ui_weather_init( void )
{
ui_MainScreen_screen_init();
ui____initial_weather_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
