// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: IO_testing

#include "../ui.h"

void ui_ScreenIOtest_screen_init(void)
{
ui_ScreenIOtest = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenIOtest, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonScreenIOtestON = lv_btn_create(ui_ScreenIOtest);
lv_obj_set_width( ui_ButtonScreenIOtestON, 181);
lv_obj_set_height( ui_ButtonScreenIOtestON, 73);
lv_obj_set_x( ui_ButtonScreenIOtestON, -11 );
lv_obj_set_y( ui_ButtonScreenIOtestON, -162 );
lv_obj_set_align( ui_ButtonScreenIOtestON, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonScreenIOtestON, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonScreenIOtestON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonScreenIOtestON, lv_color_hex(0x00ADB5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonScreenIOtestON, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelButtonScreenIOtestON = lv_label_create(ui_ButtonScreenIOtestON);
lv_obj_set_width( ui_LabelButtonScreenIOtestON, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelButtonScreenIOtestON, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelButtonScreenIOtestON, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelButtonScreenIOtestON,"GPIO UP");
lv_obj_set_style_text_font(ui_LabelButtonScreenIOtestON, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonScreenIOtestOFF = lv_btn_create(ui_ScreenIOtest);
lv_obj_set_width( ui_ButtonScreenIOtestOFF, 181);
lv_obj_set_height( ui_ButtonScreenIOtestOFF, 73);
lv_obj_set_x( ui_ButtonScreenIOtestOFF, -6 );
lv_obj_set_y( ui_ButtonScreenIOtestOFF, 100 );
lv_obj_set_align( ui_ButtonScreenIOtestOFF, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonScreenIOtestOFF, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonScreenIOtestOFF, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonScreenIOtestOFF, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonScreenIOtestOFF, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelButtonScreenIOtestOFF = lv_label_create(ui_ButtonScreenIOtestOFF);
lv_obj_set_width( ui_LabelButtonScreenIOtestOFF, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelButtonScreenIOtestOFF, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelButtonScreenIOtestOFF, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelButtonScreenIOtestOFF,"GPIO DOWN");
lv_obj_set_style_text_color(ui_LabelButtonScreenIOtestOFF, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelButtonScreenIOtestOFF, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelButtonScreenIOtestOFF, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

}
