// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: IO_testing

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenIOtest
void ui_ScreenIOtest_screen_init(void);
lv_obj_t *ui_ScreenIOtest;
lv_obj_t *ui_ButtonScreenIOtestON;
lv_obj_t *ui_LabelButtonScreenIOtestON;
lv_obj_t *ui_ButtonScreenIOtestOFF;
lv_obj_t *ui_LabelButtonScreenIOtestOFF;
lv_obj_t *ui__io_test__initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_IO_test_init( void )
{
ui_ScreenIOtest_screen_init();
ui__io_test__initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenIOtest);
}
