// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: IO_testing

#ifndef _IO_TESTING_UI_H
#define _IO_TESTING_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenIOtest
void ui_ScreenIOtest_screen_init(void);
extern lv_obj_t *ui_ScreenIOtest;
extern lv_obj_t *ui_ButtonScreenIOtestON;
extern lv_obj_t *ui_LabelButtonScreenIOtestON;
extern lv_obj_t *ui_ButtonScreenIOtestOFF;
extern lv_obj_t *ui_LabelButtonScreenIOtestOFF;
extern lv_obj_t *ui__io_test__initial_actions0;




void ui_IO_test_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
