// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Weather_Forecast

#ifndef _WEATHER_FORECAST_UI_H
#define _WEATHER_FORECAST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void UpandDown_Animation( lv_obj_t *TargetObject, int delay);
void ImgZoom_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen( lv_event_t * e);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_LabelMainScreenCityName;
extern lv_obj_t *ui_LabelMainScreenLocation;
extern lv_obj_t *ui_ImageMainScreenLocation;
extern lv_obj_t *ui_LabelMainScreenTemperature;
extern lv_obj_t *ui_ImageMainScreenCelsius;
extern lv_obj_t *ui_ImageMainScreenSunny;
extern lv_obj_t *ui_LabelMainScreenTemperatureRange;
extern lv_obj_t *ui_ImageMainScreenCelsius2;
extern lv_obj_t *ui_LabelMainScreenSunny;
extern lv_obj_t *ui_LabelMainScreenMildPollution;
extern lv_obj_t *ui_PanelMainScreenCurrent;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime1;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp1;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime2;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime3;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime4;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime5;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent2;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp2;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius1;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius2;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent3;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp3;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent4;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp4;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius3;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp5;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius4;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent5;
extern lv_obj_t *ui_PanelMainScreenCurrent1;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime6;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent6;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp6;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime7;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime8;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime9;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime10;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent7;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp7;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius5;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius6;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent8;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp8;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent9;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp9;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius7;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp10;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius8;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent10;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent11;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent12;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent13;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent14;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent15;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius9;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp11;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp12;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp13;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp14;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp15;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius10;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius11;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius12;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius13;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius14;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot1;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot2;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot3;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot4;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot5;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot6;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot7;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot8;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent1dot9;
extern lv_obj_t *ui_PanelMainScreenCurrent2;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime11;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent16;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp16;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime12;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime13;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime14;
extern lv_obj_t *ui_ImagePanelMainScreenCurrentTime15;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent17;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp17;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentCelsius15;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent18;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp18;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent19;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp19;
extern lv_obj_t *ui_LabelPanelMainScreenCurrentTemp20;
extern lv_obj_t *ui_LabelPanelMainScreenCurrent20;
extern lv_obj_t *ui____initial_weather_actions0;

LV_IMG_DECLARE( ui_img_location_png);   // assets/location.png
LV_IMG_DECLARE( ui_img_celsius_png);   // assets/celsius.png
LV_IMG_DECLARE( ui_img_sunny_png);   // assets/sunny.png
LV_IMG_DECLARE( ui_img_sunny_2_png);   // assets/sunny_2.png
LV_IMG_DECLARE( ui_img_sunset_png);   // assets/sunset.png
LV_IMG_DECLARE( ui_img_moon_png);   // assets/moon.png
LV_IMG_DECLARE( ui_img_fog_png);   // assets/fog.png
LV_IMG_DECLARE( ui_img_light_rain_png);   // assets/light_rain.png
LV_IMG_DECLARE( ui_img_thermometer_png);   // assets/thermometer.png
LV_IMG_DECLARE( ui_img_humidity_png);   // assets/humidity.png
LV_IMG_DECLARE( ui_img_cloud_cover_png);   // assets/cloud_cover.png
LV_IMG_DECLARE( ui_img_uv_png);   // assets/UV.png
LV_IMG_DECLARE( ui_img_wind_speed_png);   // assets/wind_speed.png

LV_FONT_DECLARE( ui_font_FontPuHui96);
LV_FONT_DECLARE( ui_font_FontPuhui20);
LV_FONT_DECLARE( ui_font_FontPuhui30);

void ui_weather_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
