// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Weather_Forecast

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x0066CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMainScreenCityName = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_LabelMainScreenCityName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMainScreenCityName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMainScreenCityName, -11 );
lv_obj_set_y( ui_LabelMainScreenCityName, -555 );
lv_obj_set_align( ui_LabelMainScreenCityName, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMainScreenCityName,"Shanghai");
lv_obj_set_style_text_color(ui_LabelMainScreenCityName, lv_color_hex(0x8C8989), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMainScreenCityName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMainScreenCityName, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMainScreenLocation = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_LabelMainScreenLocation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMainScreenLocation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMainScreenLocation, -10 );
lv_obj_set_y( ui_LabelMainScreenLocation, -514 );
lv_obj_set_align( ui_LabelMainScreenLocation, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMainScreenLocation,"Pudong New Area");
lv_obj_set_style_text_color(ui_LabelMainScreenLocation, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMainScreenLocation, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMainScreenLocation, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageMainScreenLocation = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_ImageMainScreenLocation, &ui_img_location_png);
lv_obj_set_width( ui_ImageMainScreenLocation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageMainScreenLocation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageMainScreenLocation, 140 );
lv_obj_set_y( ui_ImageMainScreenLocation, -513 );
lv_obj_set_align( ui_ImageMainScreenLocation, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageMainScreenLocation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageMainScreenLocation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelMainScreenTemperature = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_LabelMainScreenTemperature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMainScreenTemperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMainScreenTemperature, 43 );
lv_obj_set_y( ui_LabelMainScreenTemperature, -417 );
lv_obj_set_align( ui_LabelMainScreenTemperature, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMainScreenTemperature,"13");
lv_obj_set_style_text_color(ui_LabelMainScreenTemperature, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMainScreenTemperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMainScreenTemperature, &ui_font_FontPuHui96, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageMainScreenCelsius = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_ImageMainScreenCelsius, &ui_img_celsius_png);
lv_obj_set_width( ui_ImageMainScreenCelsius, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageMainScreenCelsius, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageMainScreenCelsius, 120 );
lv_obj_set_y( ui_ImageMainScreenCelsius, -457 );
lv_obj_set_align( ui_ImageMainScreenCelsius, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageMainScreenCelsius, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageMainScreenCelsius, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageMainScreenCelsius, lv_color_hex(0xFDFDFD), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageMainScreenCelsius, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageMainScreenSunny = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_ImageMainScreenSunny, &ui_img_sunny_png);
lv_obj_set_width( ui_ImageMainScreenSunny, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageMainScreenSunny, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageMainScreenSunny, -128 );
lv_obj_set_y( ui_ImageMainScreenSunny, -434 );
lv_obj_set_align( ui_ImageMainScreenSunny, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageMainScreenSunny, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageMainScreenSunny, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageMainScreenSunny,150);

ui_LabelMainScreenTemperatureRange = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_LabelMainScreenTemperatureRange, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMainScreenTemperatureRange, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMainScreenTemperatureRange, 34 );
lv_obj_set_y( ui_LabelMainScreenTemperatureRange, -320 );
lv_obj_set_align( ui_LabelMainScreenTemperatureRange, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMainScreenTemperatureRange,"13/6");
lv_obj_set_style_text_color(ui_LabelMainScreenTemperatureRange, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMainScreenTemperatureRange, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMainScreenTemperatureRange, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageMainScreenCelsius2 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_ImageMainScreenCelsius2, &ui_img_celsius_png);
lv_obj_set_width( ui_ImageMainScreenCelsius2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageMainScreenCelsius2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageMainScreenCelsius2, 87 );
lv_obj_set_y( ui_ImageMainScreenCelsius2, -329 );
lv_obj_set_align( ui_ImageMainScreenCelsius2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageMainScreenCelsius2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageMainScreenCelsius2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelMainScreenSunny = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_LabelMainScreenSunny, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMainScreenSunny, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMainScreenSunny, -81 );
lv_obj_set_y( ui_LabelMainScreenSunny, -322 );
lv_obj_set_align( ui_LabelMainScreenSunny, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMainScreenSunny,"Sunny");
lv_obj_set_style_text_color(ui_LabelMainScreenSunny, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMainScreenSunny, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMainScreenSunny, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMainScreenMildPollution = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_LabelMainScreenMildPollution, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMainScreenMildPollution, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMainScreenMildPollution, -17 );
lv_obj_set_y( ui_LabelMainScreenMildPollution, -265 );
lv_obj_set_align( ui_LabelMainScreenMildPollution, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMainScreenMildPollution,"mild pollution");
lv_obj_set_style_text_color(ui_LabelMainScreenMildPollution, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMainScreenMildPollution, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMainScreenMildPollution, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMainScreenCurrent = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelMainScreenCurrent, 762);
lv_obj_set_height( ui_PanelMainScreenCurrent, 189);
lv_obj_set_x( ui_PanelMainScreenCurrent, 0 );
lv_obj_set_y( ui_PanelMainScreenCurrent, -103 );
lv_obj_set_align( ui_PanelMainScreenCurrent, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelMainScreenCurrent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelMainScreenCurrent, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelMainScreenCurrent, lv_color_hex(0x1A75D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMainScreenCurrent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMainScreenCurrent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMainScreenCurrent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePanelMainScreenCurrentTime1 = lv_img_create(ui_PanelMainScreenCurrent);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime1, &ui_img_sunny_2_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime1, -299 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime1, 6 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelMainScreenCurrent1 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1, -299 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1, -50 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1,"2:00 PM");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp1 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp1, -312 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp1, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp1,"12");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp1, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp1, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePanelMainScreenCurrentTime2 = lv_img_create(ui_PanelMainScreenCurrent);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime2, &ui_img_sunny_2_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime2, -159 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime2, 6 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime3 = lv_img_create(ui_PanelMainScreenCurrent);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime3, &ui_img_sunset_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime3, -8 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime3, 6 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime4 = lv_img_create(ui_PanelMainScreenCurrent);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime4, &ui_img_moon_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime4, 141 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime4, 6 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime5 = lv_img_create(ui_PanelMainScreenCurrent);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime5, &ui_img_moon_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime5, 287 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime5, 6 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelMainScreenCurrent2 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent2, -157 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent2, -50 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent2,"4:00 PM");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent2, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent2, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp2 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp2, -173 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp2, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp2,"11");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp2, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp2, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius1 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius1, -288 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius1, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius1,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius1, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius1, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius2 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius2, -146 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius2, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius2,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius2, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius2, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent3 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent3, -6 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent3, -50 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent3,"4:58 PM");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent3, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent3, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp3 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp3, -7 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp3, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp3,"sunset");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp3, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp3, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent4 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent4, 138 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent4, -50 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent4,"5:00 PM");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent4, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent4, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp4 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp4, 127 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp4, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp4,"10");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp4, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp4, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius3 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius3, 154 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius3, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius3,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius3, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius3, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp5 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp5, 272 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp5, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp5,"10");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp5, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp5, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius4 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius4, 298 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius4, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius4,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius4, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius4, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent5 = lv_label_create(ui_PanelMainScreenCurrent);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent5, 284 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent5, -50 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent5,"6:00 PM");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent5, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent5, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMainScreenCurrent1 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelMainScreenCurrent1, 762);
lv_obj_set_height( ui_PanelMainScreenCurrent1, 311);
lv_obj_set_x( ui_PanelMainScreenCurrent1, -3 );
lv_obj_set_y( ui_PanelMainScreenCurrent1, 174 );
lv_obj_set_align( ui_PanelMainScreenCurrent1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelMainScreenCurrent1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelMainScreenCurrent1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelMainScreenCurrent1, lv_color_hex(0x1A75D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMainScreenCurrent1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMainScreenCurrent1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMainScreenCurrent1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePanelMainScreenCurrentTime6 = lv_img_create(ui_PanelMainScreenCurrent1);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime6, &ui_img_sunny_2_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime6, -301 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime6, -15 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelMainScreenCurrent6 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent6, -298 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent6, -122 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent6,"Yesterday");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent6, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent6, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp6 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp6, -309 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp6, 46 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp6,"15");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp6, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp6, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePanelMainScreenCurrentTime7 = lv_img_create(ui_PanelMainScreenCurrent1);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime7, &ui_img_fog_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime7, -154 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime7, -16 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime8 = lv_img_create(ui_PanelMainScreenCurrent1);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime8, &ui_img_sunny_2_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime8, -6 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime8, -10 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime9 = lv_img_create(ui_PanelMainScreenCurrent1);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime9, &ui_img_light_rain_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime9, 137 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime9, -13 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime10 = lv_img_create(ui_PanelMainScreenCurrent1);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime10, &ui_img_moon_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime10, 287 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime10, -15 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelMainScreenCurrent7 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent7, -157 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent7, -122 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent7, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent7,"Today");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent7, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent7, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp7 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp7, -173 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp7, 53 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp7, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp7,"14");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp7, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp7, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius5 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius5, -287 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius5, 46 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius5,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius5, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius5, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius6 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius6, -150 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius6, 52 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius6,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius6, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius6, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent8 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent8, -8 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent8, -121 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent8, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent8,"Tomorrow");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent8, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent8, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp8 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp8, -18 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp8, 53 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp8, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp8,"14");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp8, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp8, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent9 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent9, 140 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent9, -121 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent9, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent9,"Saturday");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent9, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent9, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp9 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp9, 127 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp9, 53 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp9, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp9,"14");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp9, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp9, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius7 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius7, 150 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius7, 55 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius7, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius7,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius7, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius7, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp10 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp10, 272 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp10, 58 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp10, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp10,"11");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp10, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp10, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius8 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius8, 298 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius8, 58 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius8, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius8,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius8, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius8, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent10 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent10, 283 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent10, -120 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent10, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent10,"Sunday");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent10, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent10, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent11 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent11, -299 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent11, -87 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent11, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent11,"12/27");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent11, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent11, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent12 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent12, -156 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent12, -87 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent12, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent12,"12/28");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent12, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent12, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent13 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent13, -8 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent13, -86 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent13, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent13,"12/29");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent13, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent13, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent14 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent14, 138 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent14, -84 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent14, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent14,"12/30");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent14, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent14, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent15 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent15, 282 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent15, -84 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent15, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent15,"12/31");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent15, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent15, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius9 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius9, 6 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius9, 54 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius9, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius9,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius9, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius9, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp11 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp11, -311 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp11, 136 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp11, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp11,"3");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp11, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp11, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp12 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp12, -170 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp12, 116 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp12, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp12,"7");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp12, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp12, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp13 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp13, -17 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp13, 117 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp13, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp13,"7");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp13, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp13, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp14 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp14, 128 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp14, 113 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp14, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp14,"8");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp14, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp14, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp15 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp15, 276 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp15, 119 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp15, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp15,"5");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp15, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp15, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius10 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius10, -294 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius10, 136 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius10, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius10,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius10, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius10, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius11 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius11, -152 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius11, 116 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius11, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius11,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius11, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius11, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius12 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius12, 3 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius12, 117 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius12, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius12,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius12, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius12, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius13 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius13, 146 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius13, 112 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius13, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius13,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius13, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius13, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius14 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius14, 294 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius14, 118 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius14, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius14,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius14, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius14, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot, -298 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot, 59 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot1 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot1, -299 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot1, 111 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot1,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot1, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot2 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot2, -160 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot2, 62 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot2,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot2, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot3 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot3, -160 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot3, 93 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot3,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot3, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot4 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot4, -6 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot4, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot4,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot4, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot5 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot5, -6 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot5, 92 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot5,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot5, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot6 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot6, 139 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot6, 63 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot6,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot6, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot7 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot7, 139 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot7, 90 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot7, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot7,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot7, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot8 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot8, 285 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot8, 72 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot8, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot8,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot8, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent1dot9 = lv_label_create(ui_PanelMainScreenCurrent1);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent1dot9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent1dot9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent1dot9, 285 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent1dot9, 94 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent1dot9, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent1dot9,".");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent1dot9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent1dot9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent1dot9, &ui_font_FontPuhui30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMainScreenCurrent2 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_PanelMainScreenCurrent2, 762);
lv_obj_set_height( ui_PanelMainScreenCurrent2, 189);
lv_obj_set_x( ui_PanelMainScreenCurrent2, -3 );
lv_obj_set_y( ui_PanelMainScreenCurrent2, 452 );
lv_obj_set_align( ui_PanelMainScreenCurrent2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelMainScreenCurrent2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelMainScreenCurrent2, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelMainScreenCurrent2, lv_color_hex(0x1A75D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMainScreenCurrent2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMainScreenCurrent2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMainScreenCurrent2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePanelMainScreenCurrentTime11 = lv_img_create(ui_PanelMainScreenCurrent2);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime11, &ui_img_thermometer_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime11, -304 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime11, -33 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelMainScreenCurrent16 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent16, -298 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent16, 61 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent16, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent16,"temperature");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent16, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent16, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp16 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp16, -320 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp16, 21 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp16, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp16,"10");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp16, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp16, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePanelMainScreenCurrentTime12 = lv_img_create(ui_PanelMainScreenCurrent2);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime12, &ui_img_humidity_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime12, -160 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime12, -33 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime13 = lv_img_create(ui_PanelMainScreenCurrent2);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime13, &ui_img_cloud_cover_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime13, -9 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime13, -33 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime14 = lv_img_create(ui_PanelMainScreenCurrent2);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime14, &ui_img_uv_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime14, 137 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime14, -33 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime14, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime14, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelMainScreenCurrentTime15 = lv_img_create(ui_PanelMainScreenCurrent2);
lv_img_set_src(ui_ImagePanelMainScreenCurrentTime15, &ui_img_wind_speed_png);
lv_obj_set_width( ui_ImagePanelMainScreenCurrentTime15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelMainScreenCurrentTime15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePanelMainScreenCurrentTime15, 287 );
lv_obj_set_y( ui_ImagePanelMainScreenCurrentTime15, -33 );
lv_obj_set_align( ui_ImagePanelMainScreenCurrentTime15, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelMainScreenCurrentTime15, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelMainScreenCurrentTime15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelMainScreenCurrent17 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent17, -155 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent17, 61 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent17, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent17,"humidity");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent17, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent17, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp17 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp17, -161 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp17, 21 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp17, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp17,"79%");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp17, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp17, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentCelsius15 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentCelsius15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentCelsius15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentCelsius15, -296 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentCelsius15, 21 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentCelsius15, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentCelsius15,"℃");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentCelsius15, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentCelsius15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentCelsius15, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent18 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent18, -7 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent18, 61 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent18, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent18,"cloud cover");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent18, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent18, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp18 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp18, -6 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp18, 21 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp18, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp18,"39%");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp18, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp18, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent19 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent19, 137 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent19, 61 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent19, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent19,"UV");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent19, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent19, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp19 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp19, 140 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp19, 21 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp19, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp19,"lowest");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp19, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp19, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrentTemp20 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrentTemp20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrentTemp20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrentTemp20, 284 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrentTemp20, 21 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrentTemp20, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrentTemp20,"gentle");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrentTemp20, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrentTemp20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrentTemp20, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelMainScreenCurrent20 = lv_label_create(ui_PanelMainScreenCurrent2);
lv_obj_set_width( ui_LabelPanelMainScreenCurrent20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelMainScreenCurrent20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelMainScreenCurrent20, 282 );
lv_obj_set_y( ui_LabelPanelMainScreenCurrent20, 61 );
lv_obj_set_align( ui_LabelPanelMainScreenCurrent20, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelMainScreenCurrent20,"wind speed");
lv_obj_set_style_text_color(ui_LabelPanelMainScreenCurrent20, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPanelMainScreenCurrent20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanelMainScreenCurrent20, &ui_font_FontPuhui20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
